# Generated by Django 3.1.1 on 2021-02-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Job_Title',
            new_name='JobTitle',
        ),
    ]
